// Date: 24-10-2014 14:58:35
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package dk.mrspring.kitchen.client.model.block;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPan extends ModelBase
{
    //fields
    ModelRenderer bottom;
    ModelRenderer side1;
    ModelRenderer side2;
    ModelRenderer side3;
    ModelRenderer handle;
    ModelRenderer side4;

    public ModelPan()
    {
        bottom = new ModelRenderer(this, 0, 0);
        bottom.addBox(0F, 0F, 0F, 6, 1, 6);
        bottom.setRotationPoint(-3F, 23F, -3F);
        bottom.setTextureSize(64, 32);
        bottom.mirror = true;
        setRotation(bottom, 0F, 0F, 0F);
        side1 = new ModelRenderer(this, 15, 8);
        side1.addBox(0F, 0F, 0F, 1, 1, 6);
        side1.setRotationPoint(3F, 22F, -3F);
        side1.setTextureSize(64, 32);
        side1.mirror = true;
        setRotation(side1, 0F, 0F, 0F);
        side2 = new ModelRenderer(this, 25, 0);
        side2.addBox(0F, 0F, 0F, 6, 1, 1);
        side2.setRotationPoint(-3F, 22F, 3F);
        side2.setTextureSize(64, 32);
        side2.mirror = true;
        setRotation(side2, 0F, 0F, 0F);
        side3 = new ModelRenderer(this, 0, 8);
        side3.addBox(0F, 0F, 0F, 1, 1, 6);
        side3.setRotationPoint(-4F, 22F, -3F);
        side3.setTextureSize(64, 32);
        side3.mirror = true;
        setRotation(side3, 0F, 0F, 0F);
        handle = new ModelRenderer(this, 25, 6);
        handle.addBox(0F, 0F, 0F, 4, 1, 1);
        handle.setRotationPoint(3.5F, 22.5F, -0.5F);
        handle.setTextureSize(64, 32);
        handle.mirror = true;
        setRotation(handle, 0F, 0F, 0F);
        side4 = new ModelRenderer(this, 25, 3);
        side4.addBox(0F, 0F, 0F, 6, 1, 1);
        side4.setRotationPoint(-3F, 22F, -4F);
        side4.setTextureSize(64, 32);
        side4.mirror = true;
        setRotation(side4, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        bottom.render(f5);
        side1.render(f5);
        side2.render(f5);
        side3.render(f5);
        handle.render(f5);
        side4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
