// Date: 13-07-2014 00:09:35
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer top;
    ModelRenderer rightdoor;
    ModelRenderer leftdoor;
    ModelRenderer leftknob;
    ModelRenderer rightknob;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      base = new ModelRenderer(this, 1, 0);
      base.addBox(0F, 0F, 0F, 16, 14, 14);
      base.setRotationPoint(-8F, 10F, -6F);
      base.setTextureSize(64, 64);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      top = new ModelRenderer(this, 0, 28);
      top.addBox(0F, 0F, 0F, 16, 3, 16);
      top.setRotationPoint(-8F, 7F, -8F);
      top.setTextureSize(64, 64);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      rightdoor = new ModelRenderer(this, 0, 0);
      rightdoor.addBox(-6F, 0F, -1F, 6, 12, 1);
      rightdoor.setRotationPoint(7F, 11F, -6F);
      rightdoor.setTextureSize(64, 64);
      rightdoor.mirror = true;
      setRotation(rightdoor, 0F, 0F, 0F);
      leftdoor = new ModelRenderer(this, 48, 0);
      leftdoor.addBox(0F, 0F, -1F, 6, 12, 1);
      leftdoor.setRotationPoint(-7F, 11F, -6F);
      leftdoor.setTextureSize(64, 64);
      leftdoor.mirror = true;
      setRotation(leftdoor, 0F, 0F, 0F);
      leftknob = new ModelRenderer(this, 1, 29);
      leftknob.addBox(3F, 0F, -2F, 2, 2, 1);
      leftknob.setRotationPoint(-7F, 15F, -6F);
      leftknob.setTextureSize(64, 64);
      leftknob.mirror = true;
      setRotation(leftknob, 0F, 0F, 0F);
      rightknob = new ModelRenderer(this, 8, 29);
      rightknob.addBox(-5F, 0F, -2F, 2, 2, 1);
      rightknob.setRotationPoint(7F, 15F, -6F);
      rightknob.setTextureSize(64, 64);
      rightknob.mirror = true;
      setRotation(rightknob, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    base.render(f5);
    top.render(f5);
    rightdoor.render(f5);
    leftdoor.render(f5);
    leftknob.render(f5);
    rightknob.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
